name: AdvanceDeaths
author: ErikPDev
api: 3.20.0
version: 3.0
main: ErikPDev\AdvanceDeaths\Main
softdepend:
  - EconomyAPI
  - ScoreHud

commands:
  advancedeaths:
    description: "See a player stat!"
    permission: "advancedeaths.use"
  ads:
    description: "See a player stat!"
    permission: "advancedeaths.use"
  rconAdvanceDeathsManager:
    description: "Get the top leaderboard. Implemented for RCON"
    permission: "advancedeaths.rcon"


permissions:
  advancedeaths.use:
    description: "Permission to use the AdvanceDeaths commands."
    default: true
  advancedeaths.rcon:
    description: "Permission to use the AdvanceDeaths rcon commands."
    default: op
